marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfil.urls')),
]

perfil/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('registro/', views.registro, name='registro'),
    path('registro/cliente/', views.cliente_registro, name='cliente_registro'),
    path('registro/administrador/', views.administrador_registro, name='admin_registro'),
    
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    
    path('cliente_panel/', views.cliente_panel, name='cliente_panel'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    
    path('ajax/cargar-provincias/', views.cargar_provincias, name='cargar_provincias'),
    path('ajax/cargar-distritos/', views.cargar_distritos, name='cargar_distritos'),
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from geografia.models import Departamento, Provincia, Distrito
from django.core.exceptions import ValidationError

################################################################################

# perfil.User
class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_admindisco = models.BooleanField('admin disco', default=False)
    is_active = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "Usuarios"

# perfil.Cliente
class Cliente(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    class Meta:
        verbose_name_plural = "Clientes"

# perfil.Administrador
class Administrador(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre_admin = models.CharField(max_length=255)
    nombre_negocio = models.CharField(max_length=255)
    razon_social = models.CharField(max_length=255)
    ruc = models.CharField(max_length=11, unique=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.SET_NULL, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True)
    distrito = models.ForeignKey(Distrito, on_delete=models.SET_NULL, null=True)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    correo_personal = models.EmailField(blank=True, null=True)

    def clean(self):
        # Validar que la provincia pertenece al departamento seleccionado
        if self.provincia and self.departamento and self.provincia.departamento != self.departamento:
            raise ValidationError({
                'provincia': 'La provincia seleccionada no pertenece al departamento seleccionado.'
            })
        
        # Validar que el distrito pertenece a la provincia seleccionada
        if self.distrito and self.provincia and self.distrito.provincia != self.provincia:
            raise ValidationError({
                'distrito': 'El distrito seleccionado no pertenece a la provincia seleccionada.'
            })

    class Meta:
        verbose_name_plural = "Administradores de Discoteca"

        

perfil/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth.forms import UserCreationForm
from .models import User, Cliente, Administrador
from geografia.models import Departamento, Provincia, Distrito
#from django.contrib.auth.models import User

class ClienteRegistroForm(UserCreationForm):
    telefono = forms.CharField(max_length=15, label="Teléfono")
    direccion = forms.CharField(max_length=255, label="Dirección")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': "Nombre de usuario",
            'email': "Correo electrónico",
            'password1': "Contraseña",
            'password2': "Confirmar contraseña",
        }
        widgets = {
            'username': forms.TextInput(attrs={'autofocus': False}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True
        if commit:
            user.save()
            # Creación directa de Cliente asociada al usuario
            Cliente.objects.create(
                user=user, 
                telefono=self.cleaned_data['telefono'], 
                direccion=self.cleaned_data['direccion']
            )
        return user

class AdminRegistroForm(UserCreationForm):
    # Campos adicionales
    nombre_negocio = forms.CharField(max_length=255)
    razon_social = forms.CharField(max_length=255)
    ruc = forms.CharField(max_length=11)
    direccion = forms.CharField(max_length=255)
    
    # Utilizar ModelChoiceField para generar listas desplegables
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), empty_label="Seleccione un departamento")
    provincia = forms.ModelChoiceField(queryset=Provincia.objects.none(), empty_label="Seleccione una provincia")  # Inicialmente vacío
    distrito = forms.ModelChoiceField(queryset=Distrito.objects.none(), empty_label="Seleccione un distrito")  # Inicialmente vacío

    telefono = forms.CharField(max_length=15)
    correo_personal = forms.EmailField(required=False)
    nombre_admin = forms.CharField(max_length=100, label="Nombre de administrador")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    # Asegúrate de no añadir autofocus al campo 'username'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop('autofocus', None)

        # Verificar si ya se ha pasado un valor de departamento para filtrar las provincias y distritos
        if 'departamento' in self.data:
            try:
                departamento_id = int(self.data.get('departamento'))
                self.fields['provincia'].queryset = Provincia.objects.filter(departamento_id=departamento_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Si hay un error, simplemente usa un conjunto vacío
        else:
            self.fields['provincia'].queryset = Provincia.objects.none()

        if 'provincia' in self.data:
            try:
                provincia_id = int(self.data.get('provincia'))
                self.fields['distrito'].queryset = Distrito.objects.filter(provincia_id=provincia_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Si hay un error, simplemente usa un conjunto vacío
        else:
            self.fields['distrito'].queryset = Distrito.objects.none()

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admindisco = True
        user.is_active = False  # Desactivar la cuenta por defecto
        if commit:
            user.save()
            Administrador.objects.create(
                user=user,
                nombre_admin=self.cleaned_data['nombre_admin'],
                nombre_negocio=self.cleaned_data['nombre_negocio'],
                razon_social=self.cleaned_data['razon_social'],
                ruc=self.cleaned_data['ruc'],
                direccion=self.cleaned_data['direccion'],
                departamento=self.cleaned_data['departamento'],
                provincia=self.cleaned_data['provincia'],
                distrito=self.cleaned_data['distrito'],
                telefono=self.cleaned_data['telefono'],
                correo_personal=self.cleaned_data['correo_personal'],
            )
        return user

perfil/views.py
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django import forms

from .forms import ClienteRegistroForm, AdminRegistroForm
from .models import User, Cliente, Administrador
from django.http import JsonResponse
from geografia.models import Provincia, Distrito

def cargar_provincias(request):
    departamento_id = request.GET.get('departamento_id')
    provincias = Provincia.objects.filter(departamento_id=departamento_id).order_by('nombre')
    return JsonResponse(list(provincias.values('id', 'nombre')), safe=False)

def cargar_distritos(request):
    provincia_id = request.GET.get('provincia_id')
    distritos = Distrito.objects.filter(provincia_id=provincia_id).order_by('nombre')
    return JsonResponse(list(distritos.values('id', 'nombre')), safe=False)


@login_required
def cliente_panel(request):
    return render(request, 'cliente_panel.html')

@login_required
def admin_panel(request):
    return render(request, 'admin_panel.html')

###########################################################

# INDEX PRINCIPAL
def index(request):
    return render(request, 'index.html')

# PLANTILLA REGISTRO (CLIENTE - ADMINISTRADOR DISCOTECA)
def registro(request):
    return render(request, 'registro.html')

# REGISTRO DE CLIENTE
def cliente_registro(request):
    form = ClienteRegistroForm(request.POST or None)
    
    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(request, 'Cuenta pendiente de activación por el administrador')
        return redirect('login')
    
    return render(request, 'cliente_registro.html', {'form': form})

# REGISTRO DE ADMIISTRADOR DISCOTECA
def administrador_registro(request):
    form = AdminRegistroForm(request.POST or None)
    
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('login')
    
    return render(request, 'admin_registro.html', {'form': form})

# LOGIN PANEL
class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField(label='Correo electrónico')
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            # Intenta obtener el usuario directamente aquí
            try:
                self.user = User.objects.get(email=email)
            except User.DoesNotExist:
                raise forms.ValidationError("El correo electrónico no está registrado.")

        return self.cleaned_data

def login_view(request):
    form = EmailAuthenticationForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']

        # Usar el usuario obtenido en el formulario
        user = form.user
        
        # Autenticación
        user = authenticate(username=user.username, password=password)

        if user:
            login(request, user)
            if user.is_admindisco:
                return redirect('admin_panel')
            elif not user.is_superuser:
                return redirect('cliente_panel')
        else:
            messages.error(request, 'Credenciales incorrectas')

    return render(request, 'login.html', {'form': form})

perfil/templates/admin_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel de Administrador</title>
</head>
<body>
    <h1>Bienvenido al panel del Administrador</h1>


    {% if user.is_authenticated %}
    <form id="logout-form" action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
    </form>
    {% endif %}
    
</body>
</html>

perfil/templates/admin_registro.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block body %}

<style>
    .textinput, #id_email, #id_correo_personal, #id_password1, #id_password2{
        background-color: rgb(237, 237, 237);
    }
    #id_username_helptext, #id_password1_helptext{
        display: none;
    }
    input:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 5px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    .registrar {
        background-color: black; /* Color de fondo normal (puedes ajustarlo según tus necesidades) */
        transition: background-color 0.3s ease; /* Transición suave para el cambio de color */
        color: whitesmoke;
        padding-left: 20px;
        padding-right: 20px;
        font-weight: bold;
    }

    .registrar:hover {
        background-color: rgb(76, 76, 76); /* Color de fondo en estado hover (gris) */
        color: whitesmoke;
    }
</style>

<div class="container mt-3">
    <h2 class="text-center">Registro Administrador de Negocio</h2>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="row">
            <!-- Nombre del administrador -->
            <div class="col-md-6">
                {{ form.nombre_admin|as_crispy_field }}
            </div>

            <!-- Correo electrónico -->
            <div class="col-md-6">
                {{ form.email|as_crispy_field }}
            </div>

            <!-- Correo personal -->
            <div class="col-md-6">
                {{ form.correo_personal|as_crispy_field }}
            </div>

            <!-- Nombre de la negocio -->
            <div class="col-md-6">
                {{ form.nombre_negocio|as_crispy_field }}
            </div>

            <!-- Razón social -->
            <div class="col-md-6">
                {{ form.razon_social|as_crispy_field }}
            </div>

            <!-- RUC -->
            <div class="col-md-6">
                {{ form.ruc|as_crispy_field }}
            </div>

            <!-- Dirección -->
            <div class="col-md-6">
                {{ form.direccion|as_crispy_field }}
            </div>

            <!-- Departamento -->
            <div class="col-md-6">
                {{ form.departamento|as_crispy_field }}
            </div>

            <!-- Provincia -->
            <div class="col-md-6">
                {{ form.provincia|as_crispy_field }}
            </div>

            <!-- Distrito -->
            <div class="col-md-6">
                {{ form.distrito|as_crispy_field }}
            </div>

            <!-- Teléfono -->
            <div class="col-md-6">
                {{ form.telefono|as_crispy_field }}
            </div>

            <!-- Nombre de usuario -->
            <div class="col-md-6">
                {{ form.username|as_crispy_field }}
            </div>

            <!-- Contraseña -->
            <div class="col-md-6">
                {{ form.password1|as_crispy_field }}
            </div>

            <!-- Confirmar contraseña -->
            <div class="col-md-6">
                {{ form.password2|as_crispy_field }}
            </div>
        </div>

        <!-- Botón de registro -->
        <div class="text-center">
            <button type="submit" class="btn registrar">Registrar</button>
        </div>
    </form>
</div>

<!-- Scripts jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    // Actualizar provincias cuando se selecciona un departamento
    $("#id_departamento").change(function () {
        var url = "{% url 'cargar_provincias' %}";  // URL de la vista para cargar provincias
        var departamentoId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'departamento_id': departamentoId
            },
            success: function (data) {
                $("#id_provincia").html('<option value="">Seleccione una provincia</option>');
                $("#id_distrito").html('<option value="">Seleccione un distrito</option>');  // Limpiar distritos
                $.each(data, function (key, value) {
                    $("#id_provincia").append('<option value="' + value.id + '">' + value.nombre + '</option>');
                });
            }
        });
    });

    // Actualizar distritos cuando se selecciona una provincia
    $("#id_provincia").change(function () {
        var url = "{% url 'cargar_distritos' %}";  // URL de la vista para cargar distritos
        var provinciaId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'provincia_id': provinciaId
            },
            success: function (data) {
                $("#id_distrito").html('<option value="">Seleccione un distrito</option>');
                $.each(data, function (key, value) {
                    $("#id_distrito").append('<option value="' + value.id + '">' + value.nombre + '</option>');
                });
            }
        });
    });
</script>

{% endblock %}

perfil/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <!--BOOSTRAP-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <!--PNOTIFY-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/5.2.0/PNotify.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/5.2.0/PNotify.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marketplace</title>
</head>

<body>
    <style>
        .nav-item:hover{
            background-color: rgba(147, 147, 147, 0.468);
        }
    </style>
    <header class="site-navbar navbar navbar-expand-lg navbar-light bg-dark" role="banner">
        <div class="container">
            <a class="navbar-brand font-weight-bold text-white" href="/">LOGO</a>
            <button class="navbar-toggler bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'login' %}">
                            <i class="bi bi-person-circle"></i>
                            Iniciar sesión
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'registro' %}">
                            <i class="bi bi-person-vcard-fill"></i>
                            Registro
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    

    {% block body %}

    {% endblock %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

perfil/templates/cliente_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel de Cliente</title>
</head>
<body>
    <h1>Bienvenido al panel del Cliente</h1>

    {% if user.is_authenticated %}
    <form id="logout-form" action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
    </form>
    {% endif %}
    
</body>
</html>

perfil/templates/cliente_registro.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block body %}

<style>
    #id_username_helptext, #id_password1_helptext{
        display: none;
    }
    input:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 5px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    .registrar {
        background-color: black !important; /* Color de fondo normal (puedes ajustarlo según tus necesidades) */
        transition: background-color 0.3s ease; /* Transición suave para el cambio de color */
        color: whitesmoke;
        padding-left: 20px;
        padding-right: 20px;
        font-weight: bold;
    }

    .registrar:hover {
        background-color: rgb(76, 76, 76) !important; /* Color de fondo en estado hover (gris) */
        color: whitesmoke;
    }
</style>

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="col-12 col-md-8 col-lg-6">
        <h2 class="text-center mb-2">Registro de Cliente</h2>

        <form method="POST" autocomplete="off" class="p-4 shadow rounded bg-light">
            {% csrf_token %}
            <!-- Nombre de usuario -->
            <div class="mb-3">
                {{ form.username|as_crispy_field }}
            </div>
            <!-- Correo electrónico -->
            <div class="mb-3">
                {{ form.email|as_crispy_field }}
            </div>
            <!-- Teléfono -->
            <div class="mb-3 telefono">
                {{ form.telefono|as_crispy_field }}
            </div>
            <!-- Dirección -->
            <div class="mb-3">
                {{ form.direccion|as_crispy_field }}
            </div>
            <!-- Password1 -->
            <div class="mb-3">
                {{ form.password1|as_crispy_field }}
            </div>
            <!-- Password2 -->
            <div class="mb-3">
                {{ form.password2|as_crispy_field }}
            </div>

            <!-- Botón de registro -->
            <div class="text-center">
                <button type="submit" class="btn registrar">Registrar</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const telefonoInput = document.querySelector(".telefono input");

        telefonoInput.addEventListener('input', function(e) {
            // Remover todo lo que no sean números
            let value = this.value.replace(/\D/g, '');

            // Limitar a 9 números
            if (value.length > 9) {
                value = value.slice(0, 9);
            }

            // Separar cada 3 dígitos
            let formattedValue = '';
            for (let i = 0; i < value.length; i += 3) {
                formattedValue += value.slice(i, i + 3) + ' ';
            }

            // Remover el último espacio extra si existe
            formattedValue = formattedValue.trim();

            // Actualizar el valor visual del input
            this.value = formattedValue;

            // Almacenar el valor sin formato en el campo oculto para envío
            const hiddenInput = document.createElement('input');
            hiddenInput.type = 'hidden';
            hiddenInput.name = 'telefono_raw'; // Cambia este nombre si es necesario
            hiddenInput.value = value; // Solo números

            // Remover el campo oculto anterior si existe
            const existingHiddenInput = document.querySelector("input[name='telefono_raw']");
            if (existingHiddenInput) {
                existingHiddenInput.remove();
            }

            // Agregar el nuevo campo oculto al formulario
            this.parentNode.appendChild(hiddenInput);
        });
    });
</script>

{% endblock %}

perfil/templates/index.html
{% extends "./base.html" %}

{% block body %}

<div>
    <center>
        <h1 style="padding-top: 200px;">
            Pagina Principal [INDEX]
        </h1>
    </center>
</div>

{% endblock %}

perfil/templates/login copy.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block body %}
<style>
    input:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 5px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    button{
        background-color: black !important;
        color: aliceblue !important;
    }
    button:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 2px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    button:hover{
        background-color: #4f4f4f !important;
    }
    .password-wrapper {
    position: relative;
    padding-bottom: 30px;
}

.toggle-password {
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%);
    cursor: pointer;
    font-size: 1.2rem; /* Ajusta el tamaño del icono */
    color: #6c757d; /* Color del icono */
}

</style>

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow" style="width: 350px;">
        <div class="text-center mb-4">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid" style="height: 80px;">
        </div>

        <h5 class="text-center mb-4">Iniciar sesión</h5>

        <form method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_username" class="form-label">Usuario</label>
                {{ form.username|add_class:"form-control" }}
            </div>

            <div class="mb-3 password-wrapper">
                <label for="passwordField" class="form-label">Contraseña</label>
                <input type="password" id="passwordField" name="password" class="form-control">
                <span class="toggle-password">
                    <i class="bi bi-eye" id="toggleIcon" aria-hidden="true"></i>
                </span>
            </div>

            <div class="d-grid gap-2">
                <button type="submit" class="btn">Ingresar</button>
            </div>
        </form>

        {% if messages %}
            <ul class="mt-3">
                {% for message in messages %}
                    <li class="text-danger">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

<!-- JavaScript para alternar visibilidad de la contraseña -->
<script>
    const passwordField = document.getElementById('passwordField');
    const togglePassword = document.getElementById('toggleIcon');

    togglePassword.addEventListener('click', function () {
        const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordField.setAttribute('type', type);

        // Cambiar el ícono
        this.classList.toggle('bi-eye');
        this.classList.toggle('bi-eye-slash');
    });
</script>

{% endblock %}

perfil/templates/login.html
{% extends "./base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block body %}

<!-- CSS -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/alertify.min.css"/>
<!-- Default theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/themes/default.min.css"/>

<style>
    input:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 5px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    button{
        background-color: black !important;
        color: aliceblue !important;
    }
    button:focus {
        outline: none;
        border-color: #7a7a7a !important; /* Color medio plomo */
        box-shadow: 0 0 2px #7a7a7a !important; /* Opcional, añade un efecto de sombra */
    }
    button:hover{
        background-color: #4f4f4f !important;
    }
    .password-wrapper {
    position: relative;
    padding-bottom: 30px;
}

.toggle-password {
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%);
    cursor: pointer;
    font-size: 1.2rem; /* Ajusta el tamaño del icono */
    color: #6c757d; /* Color del icono */
}

</style>

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow" style="width: 350px;">
        <div class="text-center mb-4">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="img-fluid" style="height: 80px;">
        </div>

        <h5 class="text-center mb-4">Iniciar sesión</h5>

        <form method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                {{ form.email|add_class:"form-control" }}
            </div>

            <div class="mb-3 password-wrapper">
                <label for="passwordField" class="form-label">Contraseña</label>
                <input type="password" id="passwordField" name="password" class="form-control">
                <span class="toggle-password">
                    <i class="bi bi-eye" id="toggleIcon" aria-hidden="true"></i>
                </span>
            </div>

            <div class="d-grid gap-2">
                <button type="submit" class="btn">Ingresar</button>
            </div>
        </form>

        {% if messages %}
            <ul class="mt-3">
                {% for message in messages %}
                    <li class="text-danger">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

<!-- JavaScript -->
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/alertify.min.js"></script>

<script>
    {% for message in messages %}
        alertify.set('notifier','position', 'top-right');
        alertify.error('{{ message }}');
    {% endfor %}
</script>

<!-- JavaScript para alternar visibilidad de la contraseña -->
<script>
    const passwordField = document.getElementById('passwordField');
    const togglePassword = document.getElementById('toggleIcon');

    togglePassword.addEventListener('click', function () {
        const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordField.setAttribute('type', type);

        // Cambiar el ícono
        this.classList.toggle('bi-eye');
        this.classList.toggle('bi-eye-slash');
    });
</script>

{% endblock %}